spring:
  application:
    name: bookings-service
  profiles:
    active: dev
  boot:
    admin:
      client:
        url: http://localhost:9090
        instance:
          name: Bookings API Service
server:
  servlet:
    context-path: /api/v1
  port: 9100
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS