spring:
  application:
    name: bookings-service
  profiles:
    active: dev
server:
  servlet:
    context-path: /api/v1
  port: 9100
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka