spring:
  application:
    name: movies-service
  profiles:
    active: dev
server:
  servlet:
    context-path: /api/v1
  port: 9070
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS