spring:
  application:
    name: users-service
  profiles:
    active: dev
  boot:
    admin:
      client:
        url: http://localhost:9090
        instance:
          name: Users API Service
server:
  servlet:
    context-path: /api/v1
  port: 9060
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000